### PR TITLE
Add Sarif friendly opaque rule id

### PR DESCRIPTION
**Pull request by yongyan-gh**
Related to #33 
* Assigned Sarif friendly opaque rule id.
* Export rule id to csv
* Export rule help uri to csv
* Export version to csv
* Add period to messages in csv.

### CODE REVIEW

**Comment by david-a-wheeler** [comment]
I like this approach. Please keep the "set of functions in one place"; in some cases a rule applies to many functions, and it's easier to maintain if the common ones are actually common.

Will there be a problem if a new rule is added, with a new id, and a function is moved to that new rule (with new id)? Sometimes we add a "more refined" rule to handle a function.

**Comment by yongyan-gh** [comment]
It should be fine if rule ids assigned are not changing. since rule id is the identity of rules, function name will be used as part of message text or other fields of result in SARIF. 

Even rule id changes, SARIF can support that by adding [deprecatedIds](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317840) property. 

cc @michaelcfanning pls correct me if anything is wrong with my reply.

**Review by michaelcfanning — APPROVED** [review]
:shipit:

**Comment by michaelcfanning** [comment]
This change looks good! I will next go look at your most recent candidate SARIF. Can you possibly attach a comprehensive CSV file to this issue that shows the results of this change? David was able to produce this CSV for us previously.

**Comment by yongyan-gh** [comment]
Yes i ran the tool to generated Flawfinder csv with these changes, and converted it to Sarif log with recent changes in Sarif converter.

Attached both Flawfinder csv and converted Sarif log. @michaelcfanning / @david-a-wheeler please review
[results.zip](https://github.com/david-a-wheeler/flawfinder/files/6047111/results.zip)

**Comment by michaelcfanning** [comment]
I see some good progress here. In the CSV file, there is a blank line between each record. If you introduced this, can you please fix it? If it's FF's existing behavior, of course, let's preserve it unless David wants to change.

For the SARIF:

* Why do our text regions contain leading spaces? This doesn't make sense when we are specifying start columns? It would make more sense if we were only specifying lines (where we'd expect the snippet to be a complete line.
* Will FF be able to provide a start column? I don't see this data in the CSV, only start lines.
* We need to add rule names. They should be things like `Buffer/char` (for FF1013) and `Misc\SetSecurityDescriptorDacl`. 
* Is fine to emit these in the user-facing strings, but please use the format I suggested, e.g.:
* Please add the ranking information as I suggested and remove Level from the property bag.
* Your `originalUriBaseIds` property is not populated.
* Please add the rule default configuration data for items of `warning` level (even though it's a default).
~~~
Misc/fopen: Check when opening files - can an attacker redirect it...

**Comment by yongyan-gh** [comment]
> I see some good progress here. In the CSV file, there is a blank line between each record. If you introduced this, can you please fix it? If it's FF's existing behavior, of course, let's preserve it unless David wants to change.

Yes this is existing behavior I use latest code from master branch it also generates csv with blank lines.

> 
> For the SARIF:
> 
> * Why do our text regions contain leading spaces? This doesn't make sense when we are specifying start columns? It would make more sense if we were only specifying lines (where we'd expect the snippet to be a complete line.

I think this is because Flawfinder use entire line content as context/snippet. The column number indicates the position the fcuntion starts, and it doesn't has end column.
Below are couple example results found in [test/test-patched.c](https://github.com/yongyan-gh/flawfinder/blob/users/yongyan-gh/sarifRuleId/test/test-patched.c)
| File | Line | Column | Function | Context (use · as whitespace) |
|:-:|-|-|-|-|
| .\test\test-patched.c | 36 | 2 | gets | ·gets(f); |
| .\test\test-patched.c | 49 | 3 | char | ··char d[20]; |
| .\test\test-patched.c | 95 | 20 | getopt_long | ····while ((optc = getopt_long (argc, argv, ""a"",longopts, NULL )) != EOF) { |

In this case what should we take for snippet text? the entire line? only function name?

> * Will FF be able to provide a start column? I don't see this data in the CSV, only start lines.

yes Flawfinder has start column in csv

> * We need to add rule names. They should be things like `Buffer/char` (for FF1013) and `Misc\SetSecurityDescriptorDacl`.

As discussed will add sub-id to rule id e.g. FF1001/strcpy

> * Is fine to emit these in the user-facing strings, but please use the format I suggested, e.g.:

will do.

> * Please add the ranking information as I suggested and remove Level from the property bag.

will do

> * Your `originalUriBaseIds` property is not populated.

the csv doesn't have root path, what should we use as originalUriBase path?

> * Please add the rule default configuration data for items of `warning` level (even though it's a default).

will do

> 
> ```
> Misc/fopen: Check when opening files - can an attacker redirect it...
> ```

**Comment by yongyan-gh** [comment]
@michaelcfanning 

Attached latest results with fixes except rule id and code snippet needs to be confirmed.  Please review[Result.zip](https://github.com/david-a-wheeler/flawfinder/files/6053447/Result.zip)

Exported the existing rules into excel document for better summary view. Hope it helps [Rules.zip](https://github.com/david-a-wheeler/flawfinder/files/6053450/Rules.zip)

**Comment by david-a-wheeler** [comment]
In the CSV, blank lines between hits aren't intended, so those should be removed.

I'd prefer to merge things in stages. Having changes "out of tree" for a long time risks unintentional conflicts. Can we get this to a point where I can merge it, even if it doesn't do everything?

**Comment by yongyan-gh** [comment]
@david-a-wheeler right, the output of --csv parameter doesn't produce blank line. This PR doesn't change this behavior. 
Will get this PR reviewed again by today. Thank you!

**Comment by michaelcfanning** [comment]
This looks *extremely* good! Ready to go in this version, as far as I'm concerned.

**Comment by yongyan-gh** [comment]
@david-a-wheeler can you pls review and let me know if any feedback, thanks!

**Comment by david-a-wheeler** [comment]
Reading through the differences it looks good! I'll do a test merge to make sure there are no unexpected problems, and will merge if there are no problems (or tell you if there are!). I very much appreciate your time on this.

**Comment by david-a-wheeler** [comment]
Great! I merged. It's important that "make check" (or at least "make test") pass, which it didn't because the .csv output changed. I updated the test results so that everything passes.

THANK YOU SO MUCH! What's next?

**Comment by yongyan-gh** [comment]
@david-a-wheeler thank you so much for your helps to improve Flawfinder SARIF outputs. 
Accordingly changes have been done in sarif-sdk converters.

**Comment by david-a-wheeler** [comment]
Very good. I want to work with everyone. I think the future discussion should be in: https://github.com/david-a-wheeler/flawfinder/issues/33 since this pull request has closed.

**Pull request merged**
