### PR TITLE
Enhance detection and diagnostics of LoadLibrary(Ex)

### PR DESCRIPTION
**Pull request by sylveon**
This adds a few more flags which are safe, allows combining flags without generating a warning (`LOAD_LIBRARY_SEARCH_SYSTEM32 | LOAD_LIBRARY_REQUIRE_SIGNED_TARGET` is not unsafe), and provides better guidance

### CODE REVIEW

**Comment by david-a-wheeler** [comment]
Can parameter 3 of LoadLibraryEx be an *OR*ed set of flags (using `|`?). I can't tell from documentation such as: http://winapi.freetechsecrets.com/win32/WIN32LoadLibraryEx.htm

If parameter 3 can have multiple values with `|` then this is probably too permissive. If it must be specifically one of the values listed, then this code looks great. Any idea which one it is?

**Comment by sylveon** [comment]
> Can parameter 3 of LoadLibraryEx be an ORed set of flags
[Yes](https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryexa)

**Comment by david-a-wheeler** [comment]
That's what I suspected. In that case, we should only skip it as safe if all the OR'ed flags are safe.

**Comment by david-a-wheeler** [comment]
Let me clearer - currently the patch says:

>    any(flag in hit.parameters[3] for flag in safe_search)):

I think it should split on whitespace+|, then return (skip a report) if *all* of the provided flags are in the safe_search.

Also, I think safe_search should be a set, not an array; order doesn't matter, all that matters "is this present" (this avoids linear search)? Also, the set should be set as a constant outside the function, not something that's recreated on every call. The performance doesn't matter so much in this case, but as a general style I prefer to set constants exactly once per program execution.

**Comment by sylveon** [comment]
There are flags which don't affect search order (for example `LOAD_LIBRARY_AS_IMAGE_RESOURCE`), so it gets trickier because if somebody *only* uses that flag then the unsafe search order applies, but if somebody uses it in combination with a search order flag, then the search order is safe. So it's not possible to just always allow those.

**Comment by david-a-wheeler** [comment]
@sylveon - I see! Okay, so as long as they use one of the ones listed in the "safe" list then the use as a whole is safe, correct? If I understand you correctly, it sounds like the code as written is a reasonable estimation.

**Comment by sylveon** [comment]
Correct! The only "unsafe" combination I can think of is `LOAD_WITH_ALTERED_SEARCH_PATH` (which can still search the current working directory) combined with the `LOAD_LIBRARY_SEARCH` series of flags, but the documentations explicitly calls out this combination as invalid.

If you give me a bit I'll move it to globals and add `LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR` as well to the list (this flag requires a fully qualified DLL path, making it safe as well)

**Comment by david-a-wheeler** [comment]
Sounds great! I look forward to it! Making this a constant set only once won't radically improve performance for the typical program, but I want to encourage "set constants only once" as a general style.

**Comment by sylveon** [comment]
I pushed a commit making it global. I don't think a set will improve performance since I use `in` to check if there's any flag in the parameter, and doing a split on `|` + trim to lookup in the set would probably be more expensive than a simple linear search,

**Comment by david-a-wheeler** [comment]
That's great! Merging.

**Pull request merged**
