### PR TITLE
Track curly brace level in extract_c_parameters

### PR DESCRIPTION
**Pull request by myersg86**
Add curly brace level tracking in `extract_c_paramenters` 

Resloves issue reported here: https://github.com/david-a-wheeler/flawfinder/issues/25

### CODE REVIEW

**Comment by myersg86** [comment]
@david-a-wheeler WDYT?

**Comment by david-a-wheeler** [comment]
In principle it's fine, but only if it'll eventually be used for something :-). What's the intended use?

**Comment by david-a-wheeler** [comment]
I mean, it *does* report an error, so I guess that counts as a use, but is that the only expected use?

**Comment by myersg86** [comment]
With this error included in the output when using `--csv` option, the output can't be parsed by tools expecting valid CSV. 

This MR was prompted by an investigation into https://gitlab.com/gitlab-org/gitlab/-/issues/327032 and it is designed to fix https://github.com/david-a-wheeler/flawfinder/issues/25

The use is to ensure flawfinder can produce output that can be parsed by other tools.

- https://gitlab.com/gitlab-org/gitlab/-/issues/330018

Alternatively, one could ensure that the errors aren't output when using CSV option https://github.com/david-a-wheeler/flawfinder/issues/46

Or a `--mute` option that suppresses all errors in the output of a flawfinder scan.

**Comment by david-a-wheeler** [comment]
Ah! Got it.

**Pull request merged**
