### PR TITLE
Add missing CWE(s) to FF1057's warning text

### LINKED ISSUE #71: FF1057 is missing CWE attribution in the warning text
[FF1057's text](https://github.com/david-a-wheeler/flawfinder/blob/2.0.19/flawfinder.py#L1502) is missing CWEs in the text:

```Python
    "InitializeCriticalSection":
    (normal, 3, "Exceptions can be thrown in low-memory situations",
     "Use InitializeCriticalSectionAndSpinCount instead",
     "misc", "", {}, "FF1057"),
```

As a result, when the SARIF file is generated, the `helpUri` field becomes an invalid URI:

```json
{
  "id": "FF1057",
  "name": "misc/InitializeCriticalSection",
  "shortDescription": {
    "text": "Exceptions can be thrown in low-memory situations."
  },
  "defaultConfiguration": {
    "level": "warning"
  },
  "helpUri": ")",
  "relationships": []
}
```

This leads to GitHub Code Scanning failing to accept the SARIF file:

```
Error: Unable to upload "flawfinder.sarif" as it is not valid SARIF:
- instance.runs[0].tool.driver.rules[8].helpUri does not conform to the "uri" format
```

### PR DESCRIPTION
**Pull request by mario-campos**
Closes #71 .

### CODE REVIEW

**Comment by mario-campos** [comment]
I've added [CWE-248](https://cwe.mitre.org/data/definitions/248.html) (Uncaught Exception) and [CWE-400](https://cwe.mitre.org/data/definitions/400.html) (Uncontrolled Resource Consumption), but those may not be the most accurate CWEs. Feel free to correct me or edit.

I also want to make the code more robust to handle this case again and also add a unit test.

**Comment by david-a-wheeler** [comment]
Thanks for the contribution! I'll take a look later when I get a chance.

**Comment by mario-campos** [comment]
@david-a-wheeler, have you had a chance to look into this yet?

**Comment by rbebb** [comment]
@david-a-wheeler Any update on this? Thank you for your work on this project!

**Review by sulaiman-coder — APPROVED** [review]

**Pull request merged**
