### PR TITLE
Fix Sarif output relationship target id format.

### PR DESCRIPTION
**Pull request by yongyan-gh**
The relationship target id should be string not an integer.

### CODE REVIEW

**Comment by yongyan-gh** [comment]
hi @david-a-wheeler, can you pls take a look this fix, its required for adding flawfinder Github action (#51), since the sarif with this issue will fail the validation when upload the sarif result to Github Security tab.

Flawfinder Github action use pip to install flawfinder, do we need to create a release to let pip to get latest changes? If yes can you please help to create a release?

**Comment by david-a-wheeler** [comment]
Thanks! Agreed. Merging.

**Comment by yongyan-gh** [comment]
@david-a-wheeler  can you pls also create a new release so that Github action can install the latest version. Thanks!

**Comment by david-a-wheeler** [comment]
Ah, the fun of dependencies. I'm thinking I should merge #51 and then release. Any objections?

**Comment by yongyan-gh** [comment]
sure have updated #51 pls take a look

**Pull request merged**
